/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsXaiGamesRouteImport } from './routes/projects/xai-games'
import { Route as ProjectsExPopulusRouteImport } from './routes/projects/ex-populus'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsXaiGamesRoute = ProjectsXaiGamesRouteImport.update({
  id: '/xai-games',
  path: '/xai-games',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsExPopulusRoute = ProjectsExPopulusRouteImport.update({
  id: '/ex-populus',
  path: '/ex-populus',
  getParentRoute: () => ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/ex-populus': typeof ProjectsExPopulusRoute
  '/projects/xai-games': typeof ProjectsXaiGamesRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/projects/ex-populus': typeof ProjectsExPopulusRoute
  '/projects/xai-games': typeof ProjectsXaiGamesRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/ex-populus': typeof ProjectsExPopulusRoute
  '/projects/xai-games': typeof ProjectsXaiGamesRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/projects'
    | '/projects/ex-populus'
    | '/projects/xai-games'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/projects/ex-populus'
    | '/projects/xai-games'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/projects'
    | '/projects/ex-populus'
    | '/projects/xai-games'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/xai-games': {
      id: '/projects/xai-games'
      path: '/xai-games'
      fullPath: '/projects/xai-games'
      preLoaderRoute: typeof ProjectsXaiGamesRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/ex-populus': {
      id: '/projects/ex-populus'
      path: '/ex-populus'
      fullPath: '/projects/ex-populus'
      preLoaderRoute: typeof ProjectsExPopulusRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsExPopulusRoute: typeof ProjectsExPopulusRoute
  ProjectsXaiGamesRoute: typeof ProjectsXaiGamesRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsExPopulusRoute: ProjectsExPopulusRoute,
  ProjectsXaiGamesRoute: ProjectsXaiGamesRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
